/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Anglerfish.glb -T 
Files: Anglerfish.glb [182.33KB] > F:\My Documents\Sites games\ocean-rings\public\models\player\Anglerfish-transformed.glb [58.06KB] (68%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function ModelAnglerfish(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('models/player/Anglerfish-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} scale={0.4}>
      <group name="Root_Scene">
        <group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes.Main1} />
        </group>
        <group name="Anglerfish" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh name="Anglerfish_1" geometry={nodes.Anglerfish_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Anglerfish_1.skeleton} />
          <skinnedMesh name="Anglerfish_2" geometry={nodes.Anglerfish_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Anglerfish_2.skeleton} />
          <skinnedMesh name="Anglerfish_3" geometry={nodes.Anglerfish_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Anglerfish_3.skeleton} />
          <skinnedMesh name="Anglerfish_4" geometry={nodes.Anglerfish_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Anglerfish_4.skeleton} />
          <skinnedMesh name="Anglerfish_5" geometry={nodes.Anglerfish_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Anglerfish_5.skeleton} />
          <skinnedMesh name="Anglerfish_6" geometry={nodes.Anglerfish_6.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Anglerfish_6.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/player/Anglerfish-transformed.glb')
