/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Rock Large.glb -T 
Files: Rock Large.glb [18.61KB] > F:\My Documents\Sites games\ocean-rings\public\models\decorations\Rock Large-transformed.glb [4.88KB] (74%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelRockLarge(props) {
  const { nodes, materials } = useGLTF('models/decorations/Rock Large-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock_Large_1.geometry} material={materials.Atlas} scale={100} />
    </group>
  )
}

useGLTF.preload('models/decorations/Rock Large-transformed.glb')
